primary_region = "atl"
kill_signal= "SIGQUIT"

[build]
  image = "vimagick/tinyproxy"

[[services]]
protocol = "tcp"
internal_port = 8888
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
hard_limit = 600
soft_limit = 550
[[services.ports]]
port = 8888

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
