# fly.toml app configuration file generated for fly-fixed-egress-ip-proxy on 2025-10-27T15:32:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-fixed-egress-ip-proxy'
primary_region = 'iad'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
